### ISSUE TITLE
 reference manual or article to use this framework

### ISSUE THREAD

**Issue by fa98** [Lab41/Circulo#57]
Hi,
I was wondering if there exist a reference manual or an article for this framework ?
Thank you in advance

**Comment by Lab41PaulM** [comment]
The best reference for the framework is currently the [README](https://github.com/Lab41/Circulo/tree/master/README.md).  We will update this file as we answer usage questions going forward. So if there is a question that you have that the README does not cover, please create an issue and we will address it there and update the README accordingly.
