### ISSUE TITLE
where is  VertexCoverMetric

### ISSUE THREAD

**Issue by tempcyc** [Lab41/Circulo#65]
in the metrics 'from circulo.metrics import VertexCoverMetric'
but where the 'VertexCoverMetric'?

thanks

**Comment by Lab41PaulM** [comment]
Great catch. This was a remnant of old code. We will make a fix soon,

**Comment by tempcyc** [comment]
The project is s a mazing!!
I'm looking forward to.
thanks!

**Comment by Lab41PaulM** [comment]
Let us know you have any further issues.

**Comment by tempcyc** [comment]
I am interesting in clique too!
